feat: extract docker build and push scripts (IN-304)
voiceflow/orb-common pull request #117
Opened 2023-01-04 16:37 UTC by Xavientois

**Fixes or implements IN-304**

### Brief description. What is this change?

Extract the scripts for building and pushing docker images

2023-01-04 16:47 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:73e330a22f153a5dc7d700957a2cce9358624fb2

2023-01-04 17:19 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:599e817976a7f03007e8be3965d09754d2cf00b8

2023-01-04 19:45 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:c7e4cb4d024ebb365cbcf6b84260cb49751a633f

2023-01-04 20:26 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:95fba8bcead34da50b325dc2a42da8780eec8254

2023-01-05 12:00 UTC, xavidop requested changes
approved but I want to see a run test for a specific scenario

2023-01-05 12:00 UTC, xavidop commented on src/scripts/docker/push.sh
> +        BRANCH_NAME="${CIRCLE_BRANCH//[^[:alnum:]]/-}"
can you please test this scenario?

2023-01-05 14:09 UTC, xavidop commented on src/scripts/docker/push.sh
> +        BRANCH_NAME="${CIRCLE_BRANCH//[^[:alnum:]]/-}"
SSH work!

2023-01-05 14:30 UTC, Xavientois commented on src/scripts/docker/push.sh
> +        BRANCH_NAME="${CIRCLE_BRANCH//[^[:alnum:]]/-}"
Tested:
```
b2c5a4988d3a:~# echo $CIRCLE_BRANCH; BRANCH_NAME="${CIRCLE_BRANCH//[^[:alnum:]]/-}"; echo $BRANCH_NAME
joshr/test-extracted-script/IN-304
joshr-test-extracted-script-IN-304
```

2023-01-05 14:31 UTC, xavidop approved these changes

2023-01-05 14:31 UTC, merged