fix: database track update (IN-304)
voiceflow/orb-common pull request #121
Opened 2023-01-10 15:21 UTC by Xavientois

**Fixes or implements IN-304**

### Brief description. What is this change?

When extracting the script, I assumed that all values for `image_tag` and `sem_ver_override` would be passed directly rather than as env var names, but this was not the case. This ended up breaking the flow for updating `database-cli` tracks. 

### Implementation details. How do you make this change?

This PR fixes that by allowing the value for semantic version to be passed in to the job rather than computing it within the job

### Deployment Notes

This will require dyamic config to get the correct value for the semver before running this job.

### Related PRs

- https://github.com/voiceflow/XXXXXXXXX/pull/123

2023-01-10 17:33 UTC, xavidop requested changes
when is this set? semantic_version

2023-01-10 17:34 UTC, Xavientois commented
> when is this set? semantic_version

It is passed in by the caller like here: https://github.com/voiceflow/database-cli/pull/315

2023-01-11 14:45 UTC, xavidop approved these changes

2023-01-11 22:21 UTC, merged

2023-01-11 22:22 UTC, vf-service-account commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=0.25.1