fix: extract and refactor yarn command (IN-304)
voiceflow/orb-common pull request #126
Opened 2023-01-16 16:52 UTC by Xavientois

**Fixes or implements IN-304**

### Brief description. What is this change?

Extract and refactor `yarn_command`

### Tests

2023-01-16 16:53 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:0ddafe8f182566517279b13e65b677fbc4c8bfc8

2023-01-16 17:08 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f9c66b1f9dc08119d927ebd2921a96ded0587040

2023-01-16 17:28 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:113ddce178d76384210b1ec9b5743ee0e27d7a17

2023-01-16 17:36 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:d66f051b9b422c4dddc82bf22aab9211034a4603

2023-01-16 17:44 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:2b31db981147d83556614b443d69c8f8cc7144b1

2023-01-16 19:29 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:b3d72eecbe1b5d5c55789a156ae96dc8a5c6cf71

2023-01-16 19:58 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:cc2c8b5457df2b61be6c160eff1b00cbbdefd389

2023-01-17 11:07 UTC, xavidop reviewed
can you test this in a monorepo with and without a container?

2023-01-17 11:07 UTC, xavidop commented on src/commands/yarn/yarn_command.yml
> +              <<#parameters.run_in_background>>rm -rf ${LOCK_FILE?}<</parameters.run_in_background>>
add an if-else statement here

2023-01-17 13:42 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:7891d8374d150ad2611490ab6b3f8fcd205d2614

2023-01-17 13:51 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:25cfbbc1bdba397099dfc4c6dc700cdf93996acd

2023-01-17 13:56 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:0a15150a23618b2d4fa53420adf27a316f7543b3

2023-01-17 14:06 UTC, Xavientois commented
Monorepo outside of container: https://app.circleci.com/pipelines/github/voiceflow/platform/9225/workflows/a09d7168-0c7a-4827-a093-4a70152113dc/jobs/35907?invite=true#step-117-14

Monorepo inside container: https://app.circleci.com/pipelines/github/voiceflow/creator-app/154419/workflows/3ab54612-6c02-4ec4-90a3-d01c57615bb9/jobs/630406?invite=true#step-110-29

2023-01-17 14:32 UTC, xavidop requested changes

2023-01-17 14:32 UTC, xavidop commented on src/scripts/yarn/run_command.sh
> +bash -c "${COMMAND:?}"
if the command fails, is this catch by the trap? Im wondering it because it is running in a sub-shell

2023-01-17 14:33 UTC, Xavientois commented on src/scripts/yarn/run_command.sh
> +bash -c "${COMMAND:?}"
Yup!
```
bash-3.2$ trap 'echo "fail detected"; touch /tmp/failure' ERR
bash-3.2$ bash -c "exit 1"
fail detected
bash-3.2$
```

2023-01-17 14:35 UTC, xavidop commented on src/scripts/yarn/run_command.sh
> +bash -c "${COMMAND:?}"
NOICE

2023-01-17 14:35 UTC, xavidop approved these changes
love the change!

2023-01-17 14:35 UTC, merged

2023-01-17 14:36 UTC, vf-service-account commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=0.27.1