ci: add jobs for running breaking changes tests and releasing the generated schema (DX-331)
voiceflow/orb-common pull request #130
Opened 2023-02-09 23:16 UTC by effervescentia

**Fixes or implements DX-331**

### Brief description. What is this change?

New jobs for running monorepo breaking changes tests and releasing the generated schema to the `openapi-schemas` repo

### Checklist

- [ ] changes have been validated in an ephemeral environment
- [ ] this is a breaking change and should publish a new major version
- [ ] appropriate tests have been written
- [ ] any new env vars have been added to the [notion doc](https://www.notion.so/voiceflow/Add-Environment-Variables-be1b0136479f45f1adece7995a7adbfb) and infra has been notified

2023-02-09 23:19 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:da568a8b4145dde4f256988fb8fb700eb3aa3664

2023-02-09 23:21 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:9a1c48bcaf672e5797de5c55977b2e7cb476828b

2023-02-09 23:28 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:2e08bb5343db4f33d95358d88ca23dc129c39365

2023-02-10 03:39 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:209a8983ef0d7af1afd86b9c9c127d5e6b61b4d1

2023-02-10 03:45 UTC, effervescentia commented on src/jobs/monorepo/monorepo_schema_release.yml
> +      command: cp -v --parents apps/*/openapi.json ~/schemas
copies all `apps/*/openapi.json` files with their folder structure to the `openapi-schemas` repo folder

so for `platform` it would end up copying a structure like

```
~/schemas
  - /apps
    - /admin/openapi.json
    - /identity/openapi.json
    - /analytics/openapi.json
```

2023-02-10 03:45 UTC, effervescentia commented on src/jobs/monorepo/monorepo_schema_release.yml
> +        git diff-index --quiet HEAD || git commit -m "feat: evolve ${CIRCLE_PROJECT_REPONAME} schemas"
only make a commit if there are changes

2023-02-10 03:45 UTC, effervescentia commented on src/jobs/monorepo/monorepo_test_acceptance.yml
> +      command: cp -v --parents */*/openapi.json ~/project
copy the "previous" schemas from the `openapi-schemas` repo folder into the appropriate subfolders of the monorepo

2023-02-10 03:45 UTC, effervescentia commented on src/jobs/monorepo/monorepo_test_acceptance.yml
> +        cp -v --parents apps/*/openapi.json << parameters.schema_dir >>
copy the "next" schemas and their directory structure to a directory to persist across jobs

2023-02-10 07:00 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f8073e91571be9b950309fcaf446c5d2301a6989

2023-02-10 07:19 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:a642941b84668425ea9c946d8d5e89d005264049

2023-02-10 08:28 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:65c94bd691e0f01083ad7d1412f79d09dd1b8654

2023-02-10 10:17 UTC, xavidop approved these changes

2023-02-10 11:47 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f4cfbb2de9879640e929541596cf010ccda797d4

2023-02-10 14:40 UTC, Xavientois commented on src/jobs/monorepo/monorepo_release.yml
> +    description: Steps to be run before executing the publish command
```suggestion
    description: Steps to run before executing the publish command
```

2023-02-10 14:47 UTC, Xavientois commented on src/jobs/monorepo/monorepo_schema_release.yml
> +        git diff-index --quiet HEAD || git commit -m "feat: evolve ${CIRCLE_PROJECT_REPONAME} schemas"
Hmm, I don't love that we are committing to the repo within the CI.

I don't want this to block the merge, but do you think it would be possible, instead of generating the new schema after the merge to master, to make it validate that the schema is up-to-date before merging, as part of the bors run or smth? Just a thought.

If that is not an option, can we add in a mechanism to skip these commits to master in CI?

2023-02-10 14:48 UTC, Xavientois commented on src/jobs/monorepo/monorepo_test_acceptance.yml
> +parameters:
Could we update the name of this job to reflect the fact that it also generates the schemas?

Or split the job into two single-purpose jobs?

2023-02-10 14:49 UTC, Xavientois requested changes
A couple thoughts/questions, but would be comfortable merging in its current state to not hold up this feature

2023-02-10 18:42 UTC, effervescentia commented on src/jobs/monorepo/monorepo_test_acceptance.yml
> +parameters:
I don't know if that's exactly accurate, with these changes plus [the related changes in this `platform`](https://github.com/voiceflow/platform/pull/289) I'm actually moving schema generation to the `build` step and then consuming that asset which has been persisted in the workspace downstream in the breaking changes test, readme generation and finally schema release

however the acceptance test phase does rename those `openapi.next.json` files to `openapi.json` once they've been validated, so perhaps we could rename it to better reflect that? `validate_schemas`? `prepare_schemas`?

2023-02-10 19:27 UTC, effervescentia commented on src/jobs/monorepo/monorepo_test_acceptance.yml
> +parameters:
as per our discussion, renaming to `monorepo_validate_schemas`

2023-02-10 19:30 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:124a83a357eec1136369310600eb5c0b3a4a74e6

2023-02-10 19:30 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:fae28f5a7e4a6ba59c861bbe6b4ec3c8aee82eb9

2023-02-10 19:34 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:52f59fc4e95af64606d213928c7843bb9b90d6ab

2023-02-10 20:29 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f88268e96e8355974dcf3b5c0f42b4154851b19f

2023-02-10 20:59 UTC, merged

2023-02-10 20:59 UTC, vf-service-account commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=0.29.0