feat: new e2e flow components (IN-608)
voiceflow/orb-common pull request #139
Opened 2023-03-03 17:17 UTC by Xavientois

**Fixes or implements IN-608**

### Brief description. What is this change?

This adds the new components that make up the core flow of the new e2e system:

#### Commands

- `install-vfcli`
- `set-env-name`

2023-03-03 17:19 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:64374bc67aaa4948bdae42e9201141a634975f6b

2023-03-03 18:24 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:7d6b38db0208f574518959ea4fe3c7d0bcd2ab0a

2023-03-03 18:42 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:d5cc770608e3c18833135364f7d7a26ff6e413a5

2023-03-03 18:56 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f1c2807e16173baac643cca400be6fdcbed72a09

2023-03-03 18:58 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:9ffbe3a15b22d3d1cc852f54998e3e6de84a95d9

2023-03-03 19:00 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:c2c56a71b5ff1f60c09e9c93bbfcf25b54095705

2023-03-03 20:51 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:4984f0e810d6729883ed5b4611567b63add42ea1

2023-03-03 20:54 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:cf52864692259317e822973814a627bf6f1e3bd3

2023-03-06 16:16 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:ebde69113ca98ec1d454258429f7df06923b2d45

2023-03-06 16:38 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:4d9f1addbbdce8292580978bb11d54eeb8643559

2023-03-06 17:44 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:d57c2c7ae1be733449c915abc952a6411411e51f

2023-03-06 17:55 UTC, Xavientois commented on src/jobs/e2e/run-e2e-tests.yml
> +        ls # yarn cypress:open
Don't review this section. I will replace this once I test with Ben

2023-03-06 18:07 UTC, xavidop requested changes
overall looks good, some small changes requested!

2023-03-06 18:07 UTC, xavidop commented on src/jobs/e2e/build-e2e-tests.yml
> +      path_to_clone: &e2e_repo_path /tmp/e2e-tests
add this generic reusable code after the executor

2023-03-06 18:07 UTC, xavidop commented on src/commands/vfcli/vfcli-fetch-endpoints.yml
> +    default: "creator-app auth-api test-api"
default empty

2023-03-06 18:07 UTC, xavidop commented on src/commands/vfcli/vfcli-create-env.yml
> +        <<# parameters.track-file >> --track-file << parameters.track-file >> <</ parameters.track-file >>
remove this circleci syntax, use if else instead. It is hard to maintain in the future

2023-03-06 19:25 UTC, xavidop commented on src/commands/vfcli/vfcli-fetch-endpoints.yml
> +    default: "creator-app auth-api test-api"
sounds good

2023-03-06 19:28 UTC, Xavientois commented on src/jobs/e2e/build-e2e-tests.yml
> +      path_to_clone: &e2e_repo_path /tmp/e2e-tests
I am fine to do this, but I am curious why? I personally don't think that it makes the code more readable or maintainable, but that is just my opinion. Is there another reason?

2023-03-06 19:33 UTC, Xavientois commented on src/commands/vfcli/vfcli-create-env.yml
> +        <<# parameters.track-file >> --track-file << parameters.track-file >> <</ parameters.track-file >>
Done

2023-03-06 19:36 UTC, Xavientois commented on src/jobs/e2e/build-e2e-tests.yml
> +      path_to_clone: &e2e_repo_path /tmp/e2e-tests
Moving it also fails, since the only valid keys are the following:
![Screenshot 2023-03-06 at 2 35 45 PM](https://user-images.githubusercontent.com/34867186/223212711-40d3dfeb-d108-4817-8194-a9ff2faa3020.png)
https://app.circleci.com/pipelines/github/voiceflow/orb-common/1144/workflows/0d428f5f-efda-4410-b2dd-fbc2e5de4825/jobs/2626?invite=true#step-105-9

2023-03-06 19:58 UTC, xavidop commented on src/jobs/e2e/build-e2e-tests.yml
> +      path_to_clone: &e2e_repo_path /tmp/e2e-tests
okay, lets keep it

2023-03-06 20:24 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:6039d4e09b8ef8f6838f27104e364c016b5659fc

2023-03-06 20:39 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:87ea411697d8287f4eacfebde35190a0174dbb21

2023-03-06 20:41 UTC, xavidop approved these changes

2023-03-06 20:43 UTC, merged

2023-03-06 20:44 UTC, vf-service-account commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=0.34.0