fix:use correct base revision:IN-1116
voiceflow/orb-common pull request #190
Opened 2024-01-18 21:38 UTC by edison-vflow

**Fixes or implements IN-1116**

### Brief description. What is this change?

- We are noticing that for mono repos, if a PR is not the first in a list of commits to master, when the merge to production is done, the changes for that PR are not being included in the docker images being built.
- The issue was that all branches were comparing their latest changes to the latest master.
- The fix is to use the previous CI pipeline's git revision to get the changed files and if the previous revision is not available 
     use the current revision
-  For `staging` and `trying` branches use master as base revision since the PR changes were created from master 

### Tests

- [ ]  Tested with bors branches 
- [ ] Tested with non bors branches

2024-01-18 21:42 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:c873c100d53e747a65f1edd545d7d55e08390898

2024-01-18 21:47 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:335dce1695fa10112bbaedf40e6c9d506208e4a0

2024-01-18 21:50 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:75972af1f991fef60b6b5e273066ca062c647935

2024-01-18 21:55 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:2411a0e4c5339d948bfdb51d876440fde823a634

2024-01-18 22:11 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:dfc6c8ba16446abd72b6c5ffb65e73a78230fab3

2024-01-19 12:39 UTC, xavidop requested changes

2024-01-19 12:39 UTC, xavidop commented on src/commands/utils/get_changed_files.yml
> +          BASE_REVISION="master"
you still need this?
```
 environment:
        BASE_REVISION: '<< parameters.base_revision >>'
```

2024-01-19 15:53 UTC, edison-vflow commented on src/commands/utils/get_changed_files.yml
> +          BASE_REVISION="master"
We had that parameter in order to allow the step to pass a value from the service `.config.yaml ` 
Its not needed anymore because the base_revision is now computed.
What we were needing the parameter for is now being fulfilled in the new step , `compute_base_revision.yml` which is run before the get-changed-files step.

If we look in creator-app, the execution sequence is now: 
```

 - vfcommon/compute_base_revision:
                base_revision: >-
                          << pipeline.git.base_revision >>
                          <<^ pipeline.git.base_revision >>
                            << pipeline.git.revision >>
                          <</ pipeline.git.base_revision >>
                git_branch:  << pipeline.git.branch >>
  - vfcommon/get_changed_files
```
            
In `compute_base_revision.yml` we have these : 

```
environment:
        BASE_REVISION: '<< parameters.base_revision >>'
        GIT_BRANCH: '<< parameters.git_branch >>'
```

2024-01-19 16:01 UTC, xavidop approved these changes
Sounds good! Perfect!

2024-01-19 16:46 UTC, merged