fix: cater for edge case base branches that dont exist:IN-1116
voiceflow/orb-common pull request #191
Opened 2024-01-19 22:15 UTC by edison-vflow

* IN-1116

### Brief description. What is this change?

* Cater for base branches that expire or when we rebase and the ancestor of current branch changes from what it was.

2024-01-19 22:17 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:32ae3fc916dc0284e167834aa21aa8ba2eff81c0

2024-01-19 23:03 UTC, Xavientois approved these changes

2024-01-19 23:03 UTC, Xavientois approved these changes

2024-01-19 23:05 UTC, xavidop requested changes

2024-01-19 23:05 UTC, xavidop commented on src/commands/utils/compute_base_revision.yml
> +          if [ -z "$(git rev-list $GIT_BRANCH  | grep $BASE_REVISION 2> /dev/null)" ]; then
can you add a comment explaining what does this line?

2024-01-19 23:06 UTC, theProf requested changes

2024-01-19 23:06 UTC, theProf commented on src/commands/utils/compute_base_revision.yml
> +          if [ -z "$(git rev-list $GIT_BRANCH  | grep $BASE_REVISION 2> /dev/null)" ]; then
this looks like a way of testing if a commit exists? you may want to try:

`git rev-parse -q --verify "$BASE_REVISION^{commit}"`

2024-01-19 23:06 UTC, edison-vflow commented on src/commands/utils/compute_base_revision.yml
> +          if [ -z "$(git rev-list $GIT_BRANCH  | grep $BASE_REVISION 2> /dev/null)" ]; then
Sure @xavidop

2024-01-19 23:15 UTC, edison-vflow commented on src/commands/utils/compute_base_revision.yml
> +          if [ -z "$(git rev-list $GIT_BRANCH  | grep $BASE_REVISION 2> /dev/null)" ]; then
@theProf , I did try a lot of permutations of verifying that a commit exists.
I basically need something that will tell me that the base revision we want to use for that branch exists before we use it.
the -q option silences any output making it unusable.
The other thing is that we need the base itself so checking if the base exists in a branch is the simplest way

2024-01-19 23:21 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:5fe72bdfadeae02915fae2505643f10c5d6cca1f

2024-01-19 23:25 UTC, edison-vflow commented on src/commands/utils/compute_base_revision.yml
> +          if [ -z "$(git rev-list $GIT_BRANCH  | grep $BASE_REVISION 2> /dev/null)" ]; then
@xavidop , comments added

2024-01-19 23:27 UTC, xavidop approved these changes

2024-01-19 23:32 UTC, theProf approved these changes

2024-01-19 23:32 UTC, theProf commented on src/commands/utils/compute_base_revision.yml
> +          if [ -z "$(git rev-list $GIT_BRANCH  | grep $BASE_REVISION 2> /dev/null)" ]; then
>  the -q option silences any output making it unusable.

that's not true by the manual and trial, but go with what's working for you to unblock

>         -q, --quiet
>            Only meaningful in --verify mode. Do not output an error message if the first argument is not a valid object name; instead exit
>            with non-zero status silently. SHA-1s for valid object names are printed to stdout on success.

```ogrady@Gregs-MacBook-Pro creator-app % git rev-parse -q --verify 785746976712c66a02b0cd1308a2e097b5a6586f^{commit}
785746976712c66a02b0cd1308a2e097b5a6586f
ogrady@Gregs-MacBook-Pro creator-app % git rev-parse -q --verify 785746976712c66a02b0cd1308a2e097b5a6586b^{commit}
ogrady@Gregs-MacBook-Pro creator-app %
```

2024-01-20 00:25 UTC, merged

2024-01-20 00:26 UTC, vf-service-account commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=0.52.1