feat: docker buildx for target stages (PL-664)
voiceflow/orb-common pull request #194
Opened 2024-02-02 21:06 UTC by theProf

**Fixes or implements PL-664**

### Brief description. What is this change?

Add step to target a stage of a Dockerfile in buildx

### Implementation details. How do you make this change?

Want to bring forward our usage of Docker/buildkit toolings and features with more control/split ownership of building between dev and infra

Remote Cache Registry:
- Default naming scheme is `<image repo>:cache-<branch>`
- Default cache-from: current branch cache and master cache
- Only allow 1 cache per branch
  - likely needs a way to cleanup the remote cache after it's been merged and built on master, if the storage is an issue

DLC:
- Default builder name is `builder-<branch>` as a key

### Related PRs

- https://github.com/voiceflow/creator-api/pull/1406

2024-02-05 21:37 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:091dc70a7c002a6774574377febd0e4f0c84e583

2024-02-07 19:14 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:95a53b28dfaaaafb0433765c4e6b4d9338834553

2024-02-08 16:11 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:e76115951783764fbfb9cc5a166874cf076b164b

2024-02-08 17:33 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:e76115951783764fbfb9cc5a166874cf076b164b

2024-02-09 17:47 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:0183543aee5a1bed0eafec17a18e0f1e1fc87990

2024-02-12 19:11 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:dea9bc4127fac991ec50a5f6efaaa14828172f62

2024-02-12 19:22 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:fc0e151e71b1887b5145c0775636c56e21c15a0f

2024-02-12 19:30 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:04f93baf1e97e3458d86ad2ce32f782a2c1c1cac

2024-02-12 19:40 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:e5920f043b58589d5693f944346429154e120d54

2024-02-12 20:59 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:d60d8e33aaf0c72733a84fdc1a50b2f21b25ff4a

2024-02-13 01:38 UTC, theProf commented on src/commands/docker/staged_buildx.yml
> +      Consider this the key for CircleCI DLC
this is currently not utilized and should be in some respect, along with buildx pruning

2024-02-13 01:39 UTC, theProf commented on src/scripts/docker/staged_buildx.sh
> +echo "NO_CACHE_FILTER: ${NO_CACHE_FILTER:=prod}"
default `prod` since it is the last stage and will always want to be non-cached, but also because not specifying a stage results in not using the cache for _any_ stage

2024-02-13 18:45 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:21f917721e68b63e91792a51b4b1f0bdf8fe0e76

2024-02-13 18:47 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f61904b8c91b5b78c22f62819bf51275dc73c00f

2024-02-14 13:23 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f235ff872a5725b573762373c0ded1589a5797b4

2024-02-14 13:39 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:34f31ec39cd468b17a755f40322189c66cf5d281

2024-02-14 13:57 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f9ec1bb392d6ac686cc4ee2c6dc8db72e7ee2e50

2024-02-14 14:25 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:2d50ab997d3d82ce3c86902a3856ed2c807fdf9e

2024-02-14 14:27 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:1822fc77851d84a2f4e004ac241197c8ef561140

2024-02-14 20:17 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:3e5d72897f0488df6c4125db77f57a836c1c2702

2024-02-14 20:47 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:1822fc77851d84a2f4e004ac241197c8ef561140

2024-02-14 21:26 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:548fc19309131cfa5b02289a05d5775612776df8

2024-02-14 21:47 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:eb1c975c86b5029728dc97f7c678dd71d4ec884d

2024-02-14 22:01 UTC, edison-vflow commented on src/scripts/docker/staged_buildx.sh
> +test "${CLEANUP_IMAGE-}" -eq 1 && echo "Deleting image" && docker image rm "${IMAGE_REPO}:${IMAGE_TAG}" || echo "Done"
Will this be in the final version to be merged, the test line and where we manually remove things from the image cache ?

2024-02-14 22:11 UTC, edison-vflow commented
**Changes are looking good !**

I would recommend we choose a few repos like `creator-app` , `platform`, `general-runtime` where we use the dev orb that is produced by this PR and we just to sanity checks that if there are actual changes across 

1. All services in a mono repo (   `creator-app`, `platform` ) the build using the new job/command and modified job/command still works (After this test, will be glad to approve) 
    a. When doing these tests to ensure that the orb jobs are triggered, we will need to have the component track for that PR so that our job is actually triggered, otherwise it fails silently and shows as if the steps ran successfully
    b. I can assist when you start creating PR's on the other service repos that consume the development ORB when testing
3. If build passes, do we want to take it a step further to deploy the created image (I think this is optional)

2024-02-14 22:42 UTC, trs commented on src/commands/docker/staged_buildx.yml
> +      Consider this the key for CircleCI DLC
What's DLC stand for again?

2024-02-14 22:54 UTC, theProf commented
> **Changes are looking good !**
> 
> I would recommend we choose a few repos like `creator-app` , `platform`, `general-runtime` where we use the dev orb that is produced by this PR and we just to sanity checks that if there are actual changes across
> 
>     1. All services in a mono repo (   `creator-app`, `platform` ) the build using the new job/command and modified job/command still works (After this test, will be glad to approve)
>        a. When doing these tests to ensure that the orb jobs are triggered, we will need to have the component track for that PR so that our job is actually triggered, otherwise it fails silently and shows as if the steps ran successfully
>        b. I can assist when you start creating PR's on the other service repos that consume the development ORB when testing
> 
>     2. If build passes, do we want to take it a step further to deploy the created image (I think this is optional)

agreed. I've started with `creator-api` as a single repo, and as a follow up have `platform` in the works for a monorepo with sdks as well. `creator-api` is currently tracked for builds, and seems to be succeeding as well.

2024-02-14 22:58 UTC, theProf commented on src/scripts/docker/staged_buildx.sh
> +test "${CLEANUP_IMAGE-}" -eq 1 && echo "Deleting image" && docker image rm "${IMAGE_REPO}:${IMAGE_TAG}" || echo "Done"
the purpose of it is to clean out build artifacts after they are used if not needed for next steps (so we don't want to include in caches/etc)

I wasn't sure if this should be a flag, or if we should instead add a `post_steps` `type: steps` that allows to be run after at the command level. or a cleanup command that can be run after that does the tasks. i want to try and avoid putting too much logic in a single `script` and go for a more composition approach to keep the scripts from getting too disjointed/duplicated

2024-02-14 23:22 UTC, edison-vflow commented on src/commands/docker/staged_buildx.yml
> +      Consider this the key for CircleCI DLC
It stands for Docker Layer Caching 

- https://circleci.com/docs/docker-layer-caching/
- https://circleci.com/blog/config-best-practices-docker-layer-caching/
- https://support.circleci.com/hc/en-us/articles/4407580027675-Docker-Layer-Caching-FAQ

2024-02-14 23:23 UTC, edison-vflow commented on src/scripts/docker/staged_buildx.sh
> +test "${CLEANUP_IMAGE-}" -eq 1 && echo "Deleting image" && docker image rm "${IMAGE_REPO}:${IMAGE_TAG}" || echo "Done"
Yeah, sounds like having it as a command called as a `post_step` will be more composable

2024-02-15 09:44 UTC, xavidop requested changes
super small changes! this is promising! great job @theProf

2024-02-15 09:44 UTC, xavidop commented on src/scripts/docker/staged_buildx.sh
> +echo "NO_CACHE_FILTER: ${NO_CACHE_FILTER:=prod}"
I will rename prod to runner, since prod can be confusing (production track, production branch). the stager are usually builder and then runner

2024-02-15 09:44 UTC, xavidop commented on src/scripts/docker/staged_buildx.sh
> +test "${CLEANUP_IMAGE-}" -eq 1 && echo "Deleting image" && docker image rm "${IMAGE_REPO}:${IMAGE_TAG}" || echo "Done"
agreed with @edison-vflow

2024-03-11 21:51 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:ce132e71306600a02150d85646e60ce5001d26a9

2024-03-13 11:01 UTC, xavidop commented on src/scripts/docker/staged_buildx.sh
> +docker buildx use "${BUILDER-}"
what does the `-` mean?

2024-03-13 11:02 UTC, xavidop approved these changes

2024-03-19 02:16 UTC, theProf commented on src/scripts/docker/staged_buildx.sh
> +docker buildx use "${BUILDER-}"
> 1. Expand to '' when var is either unset or null.
> 2. Expand to the value of the var (when var has a value).
[SO good explanation of confusing manual documentation](https://stackoverflow.com/a/32675207)

2024-03-19 02:16 UTC, merged

2024-03-19 02:17 UTC, vf-service-account commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=0.58.0