feat: integrating e2e pooling into VFCLI
voiceflow/orb-common pull request #215
Opened 2024-04-24 07:14 UTC by junydania

**Fixes or implements IN-974**

### Brief description. What is this change?

Integrating VFCLI e2e pooling into the pipeline

### Implementation details. How do you make this change?

### Setup information

### Deployment Notes

### Related PRs

- https://github.com/voiceflow/XXXXXXXXX/pull/123

### Checklist

- [ ] Breaking changes have been communicated, including:
    - New required environment variables
    - Renaming of interfaces (API routes, request/response interface, etc)
- [ ] New environment variables have [been deployed](https://www.notion.so/voiceflow/Add-Environment-Variables-be1b0136479f45f1adece7995a7adbfb)
- [ ] Appropriate tests have been written
    - Bug fixes are accompanied by an updated or new test
    - New features are accompanied by a new test

2024-04-24 08:44 UTC, xavidop requested changes

2024-04-24 08:44 UTC, xavidop commented on src/commands/vfcli/vfcli-delete-env.yml
> +            vfcli pool release-env --env-name "$env_name"
`vfcli env resume "$env_name" --interactive false --track-file "<< parameters.track-file >>" --no-wait`

--no-wait: do not wait to have all the deployments ready
--track-file: all components

```
vfcli env resume "$env_name" --interactive false
vfcli track attach --branch master --component all --name "$env_name" --interactive false
```

2024-04-24 08:44 UTC, xavidop commented on src/commands/vfcli/vfcli-suspend-env.yml
> +          vfcli env suspend "<< parameters.env-name >>" --interactive false --track-file "<< parameters.track-file >>"
refactor this

2024-04-24 08:44 UTC, xavidop commented on src/commands/vfcli/vfcli-create-env.yml
> +      name: Get Free Environment
rename this command vfcli create-or-get-free-env-from-pool

add a parameter to force always the env creation

2024-04-24 08:44 UTC, xavidop commented on src/commands/vfcli/vfcli-create-env.yml
> +          echo "Environment from pool being used: $ENV_NAME"
set the env to be in used with the pool

2024-04-24 08:44 UTC, xavidop commented on src/commands/vfcli/vfcli-create-env.yml
> +        free_env=$(vfcli get-free-env --output json)
add the pool-id as a parameter of this job, by default, the e2e one

2024-04-24 08:44 UTC, xavidop commented on src/commands/vfcli/vfcli-delete-env.yml
> +            vfcli pool release-env --env-name "$env_name"
add the pool-id as a parameter of this job, by default, the e2e one

2024-04-24 08:44 UTC, xavidop commented on src/commands/vfcli/vfcli-delete-env.yml
> +  - attach_workspace:
rename it to delete-env-or-release-env

2024-04-24 08:44 UTC, xavidop commented on src/commands/vfcli/vfcli-delete-env.yml
> +  - attach_workspace:
add a flag to enforce env deletion just in case we want to re-use this job to delete an env

2024-04-25 12:44 UTC, junydania commented on src/commands/vfcli/vfcli-create-env.yml
> +        free_env=$(vfcli get-free-env --output json)
Done

2024-04-25 12:49 UTC, junydania commented on src/commands/vfcli/vfcli-delete-env.yml
> +            vfcli pool release-env --env-name "$env_name"
Applied

2024-04-25 12:51 UTC, junydania commented on src/commands/vfcli/vfcli-delete-env.yml
> +  - attach_workspace:
done

2024-04-25 13:05 UTC, junydania commented on src/commands/vfcli/vfcli-delete-env.yml
> +            vfcli pool release-env --env-name "$env_name"
Done

2024-04-25 13:09 UTC, junydania commented on src/commands/vfcli/vfcli-delete-env.yml
> +  - attach_workspace:
Done

2024-04-25 13:17 UTC, junydania commented on src/commands/vfcli/vfcli-create-or-get-free-env-from-pool.yml
> +            result=$(vfcli get-free-env --output json)
@xavidop  I was thinking it just fetches from any available pool. However since we would different pools for e2e and review. I think I should enforce this to pool from e2e pool.  Will refactor VFCLI now

2024-04-25 13:33 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:54783a4ae81cee9a924f15979f83204244d65bf7

2024-04-26 14:48 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:4d227b9b7728cc656cf63934a3403b2f0e84a084

2024-04-29 13:45 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:938ce7da5038c7eb32ecafd1c681fa3da8ba74b6

2024-04-29 18:06 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:17668bb7bd15477e9ef462d062ef515838434f40

2024-04-29 18:25 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:e5fb4d9784838854e1a032fd2cf210d4edb29da6

2024-04-29 19:14 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:4b5c661a6a0562524a82b97c6884ce70f73f1c1c

2024-04-30 13:19 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:6996ea59036bf6bd287775c8249ea857e97b65fd

2024-04-30 13:54 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:b5941e6d2537c98c43e4f703bebab34a2bdc1a61

2024-04-30 14:20 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:99945746eeee74d236ba790b79f3cd2d0e14fdc0

2024-04-30 15:21 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:c347f3503d638152c786cd206381283dfc17f50e

2024-04-30 17:57 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:14943bce2d03537c97aa4062fc3493f53ded24ac

2024-05-02 13:16 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:c34f4cc7ef579870cf3ca3950803da4e46cc50b8

2024-05-02 15:38 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:fa93f7b7cb9111a27581fdcf064849b1eb42a339

2024-05-02 17:05 UTC, edison-vflow commented on src/jobs/smoke/run-smoke-tests.yml
> +  - run:
Should we put some comments here
About the fact that we are checking if pool env is set, otherwise use the same value etc 

Like why we did this change.
Somewhere down the line, it would only take people with context to know what this check is doing

2024-05-02 18:43 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:9fd35c4fa7b284bbfe193eb826dc094e9b7b941d

2024-05-02 19:17 UTC, merged

2024-05-02 19:18 UTC, vf-service-account commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=0.66.0