feat: use git shallow clone (IN-1006)
voiceflow/orb-common pull request #227
Opened 2024-05-03 20:47 UTC by edison-vflow

### Fixes or implements 
* Linear [IN-1006 ](https://linear.app/voiceflow/issue/IN-1006/use-shallow-clone-instead-of-checkout)

### Brief description. What is this change?
* We can speed up builds by up to and shave off 30 seconds, eg for repos like creator-app 
* Where it takes 30 seconds to clone, it will now take 1 second 
### Implementation details. How do you make this change?
* Do shallow clones for both branches and tags 

### Checklist

- [ ] Tested on creator-app
- [ ] Tested on database-cli

2024-05-03 21:48 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:de5a3aefde57b58be333cfddc5b41bc3f9970947

2024-05-03 22:01 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:d45a49b0322916e0a39ef6d8255aeb1bce263f2f

2024-05-03 22:18 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:07d2cfd663ec477d8714d7336e2e50541dc33bcf

2024-05-03 23:11 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:af904b639857eb579bfcfdd58a79c6727d5143ec

2024-05-03 23:22 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:8eb9f5563bd8eb7b4cf32c04f2d51d36fd5528e9

2024-05-03 23:28 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:d06f42b4809a4892e438809c8a75e2df007b9aa3

2024-05-04 00:51 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:42fbf0235a72acba3604f8dc94571406aa75a8dc

2024-05-04 21:35 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:85b57b1712eab216290f611b0105674a1f1d83d7

2024-05-04 21:40 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:7373bc71628ae37637abd6a200605dc889e9fa8c

2024-05-08 00:25 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:5b4893dbf6e2386f52d53075ccf8b423ba3ff4c5

2024-05-08 04:23 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:374beaf1c4fe3b052655f3b2ef7c030d33678a99

2024-05-08 04:58 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:aa5f9807e3797c457fc79192b2ffd02283ab2f57

2024-05-08 20:25 UTC, xavidop requested changes

2024-05-08 20:25 UTC, xavidop commented on src/commands/utils/checkout_shallow_clone.yml
> +        git fetch origin master --depth=2
can you please add a comment here that explains this: https://www.notion.so/voiceflow/Shallow-clone-across-all-repos-9e4f6402bcbe4f3f925f583c61c0ec82?pvs=4#fe8a620a6d3a4ce89641482ba80e7d15

2024-05-08 20:55 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:60c775256360db706a2bc1683e6670aee3b2642c

2024-05-08 20:55 UTC, edison-vflow commented on src/commands/utils/checkout_shallow_clone.yml
> +        git fetch origin master --depth=2
> can you please add a comment here that explains this: https://www.notion.so/voiceflow/Shallow-clone-across-all-repos-9e4f6402bcbe4f3f925f583c61c0ec82?pvs=4#fe8a620a6d3a4ce89641482ba80e7d15

Comments have been added

2024-05-08 20:58 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:ee592a2affaaa28f0da9c3ad7a0103f877896bdd

2024-05-08 21:13 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:a3e92cdcd3e897461c4a8d207e8604df03b73ff9

2024-05-08 21:38 UTC, xavidop approved these changes

2024-05-08 22:19 UTC, merged