fix: always enforce env release
voiceflow/orb-common pull request #229
Opened 2024-05-08 15:59 UTC by junydania

**Fixes or implements IN-1048**

### Brief description. What is this change?

### Implementation details. How do you make this change?

### Setup information

### Deployment Notes

### Related PRs

- https://github.com/voiceflow/XXXXXXXXX/pull/123

### Checklist

- [ ] Breaking changes have been communicated, including:
    - New required environment variables
    - Renaming of interfaces (API routes, request/response interface, etc)
- [ ] New environment variables have [been deployed](https://www.notion.so/voiceflow/Add-Environment-Variables-be1b0136479f45f1adece7995a7adbfb)
- [ ] Appropriate tests have been written
    - Bug fixes are accompanied by an updated or new test
    - New features are accompanied by a new test

2024-05-08 16:01 UTC, xavidop approved these changes

2024-05-10 10:25 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:03211faa207c1009e01200d7a8a9fcde63f4c4e0

2024-05-10 11:59 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:5d120b4777711fd0052453c04dfaa033470ec95e

2024-05-29 10:27 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:734067a2007672cccedb6c568795df57c1226e67

2024-05-29 10:29 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:25d2bfc2726696eee8f02f4b5d18be4b571c8c2a

2024-05-30 21:57 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:489bcd188bf3caba791a49be6ee24901fac58a52

2024-05-31 07:36 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:82a259412be512a0db464fffc4d8d8d938c1ad91

2024-05-31 08:03 UTC, xavidop approved these changes

2024-06-02 16:42 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:cdaba74a0c89a3f6ac9f68a71f35c8b73ca72e36

2024-06-02 19:18 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:9bc1d032e5e32d60e7c8e3cde0f77b3ccd454862

2024-06-02 19:20 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:ad7c2e0e897909b00efe9b60dacd1e25e59edfa8

2024-06-02 19:30 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:b265344bd515bd1f0120e5c04f8ec8ac8bbfbb18

2024-06-02 19:50 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:90441870fc7d25c92e64d2144aec832a955ab155

2024-06-02 20:06 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:dcdcb98d862b957675baa00531a0d3d426f9a222

2024-06-02 20:07 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:9dd988775b99a4ea33fac8a9f636995406e136ac

2024-06-02 20:20 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:4f6358da8fd74122435c7777bfd1cb48603222ed

2024-06-02 20:34 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:90bf15cad2fe5d8ee021b49d6043ae8bb3e12ea1

2024-06-02 20:58 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:15fdd8a74fbbf2c1f5bbc2e6ad0b8b35eba6bb72

2024-06-02 21:09 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:647183e3a0d7b5cb27933f80676eb7756265344f

2024-06-02 21:22 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:112eb59796ec192d1218aeb0eb55a9c8d032132b

2024-06-02 21:43 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:3da7a4fd0ef77f80bb5148e23c06b4cd56782351

2024-06-02 21:45 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:e39f3c154074ef2dcbc89ffcd775c4f17a2fe2d2

2024-06-02 22:16 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:2255ba60c604675e15c3b0e44e89a04d2b2edd7c

2024-06-02 22:17 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:7228f4d5e7bb14f93b83cbc878e89fda3dcd3e7b

2024-06-03 10:18 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f083a891e7419fb6a779e3de7c9d085c193d4ff1

2024-06-03 10:50 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:926b7b20ab80e467f55bd0fba60f6d3e11f6a04a

2024-06-03 11:08 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:eee77224e20d41c6cc94cdf82453c80d0e8b3d69

2024-06-03 11:10 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:8d0aa91ba13405053c6aab5c690e10fb2677794f

2024-06-03 11:22 UTC, xavidop requested changes

2024-06-03 11:22 UTC, xavidop commented on src/commands/vfcli/vfcli-create-or-get-free-env-from-pool.yml
> +              echo "create" > workspace/skip_create_env
I think we should use only env_name.txt with the key word "create", it would be easier

2024-06-03 11:22 UTC, xavidop commented on src/commands/vfcli/vfcli-create-or-get-free-env-from-pool.yml
> +              echo "create" > workspace/skip_create_env
and use the cache in the create env so everything is consistent

2024-06-03 11:36 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:c20309be540c408842c91b68fdf0febeb3364e23

2024-06-03 11:38 UTC, junydania commented on src/commands/vfcli/vfcli-create-or-get-free-env-from-pool.yml
> +              echo "create" > workspace/skip_create_env
@xavidop  We can use cache all through and remove workspaces. However,  the env_name.txt file is meant for storing just the env name and used across other job while we have another file to store the condition to either create or skip.

2024-06-03 11:53 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:a3da7bccd5ea5fe3515b03b7277e9c4e5a5d1bcd

2024-06-03 11:56 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:54c409e7cadae9b670724baa3b66088024740da0

2024-06-03 12:10 UTC, junydania commented on src/commands/vfcli/vfcli-create-or-get-free-env-from-pool.yml
> +              echo "create" > workspace/skip_create_env
Nevermind. Switched to using just env_name.txt

2024-06-03 13:32 UTC, xavidop requested changes

2024-06-03 13:32 UTC, xavidop commented on src/commands/vfcli/vfcli-create-or-get-free-env-from-pool.yml
> +              echo "create" > env_name.txt  # Write 'null' to indicate no environment was found
Write 'create' to indicate no environment was found

2024-06-03 13:32 UTC, xavidop commented on src/commands/vfcli/vfcli-create-or-get-free-env-from-pool.yml
> +        if [[ $(cat env_name.txt) == "create" ]]; then
we should modify the en_name.txt with the environment created

2024-06-03 13:32 UTC, xavidop commented on src/commands/vfcli/vfcli-create-or-get-free-env-from-pool.yml
> +        if [[ $(cat env_name.txt) == "create" ]]; then
and save the cache

2024-06-03 13:32 UTC, xavidop commented on src/commands/vfcli/vfcli-delete-or-release-env.yml
> +          fi
why are we setting this to "create"?

2024-06-03 13:32 UTC, xavidop commented on src/commands/vfcli/vfcli-suspend-env.yml
> +        if [[ "$env_name" == "create" ]]; then
why are we checking this to "create" is this wrong?

2024-06-03 14:02 UTC, edison-vflow commented
@junydania , would using `when: always ` capability of circleci steps work, to run the cleanup instead of waiter jobs ?

2024-06-03 14:16 UTC, edison-vflow commented
> @junydania , would using `when: always ` capability of circleci steps work, to run the cleanup instead of waiter jobs ?

Thanks for explaining about the parallel runs complication @junydania 
The waiter implementation will be our best bet then

2024-06-03 14:20 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:d0a0af3bf249d3b7a1ccd3739228f5603cbebe9c

2024-06-03 16:04 UTC, xavidop approved these changes

2024-06-03 16:09 UTC, merged

2024-06-03 16:10 UTC, vf-service-account commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=0.71.1