feat(update-track): allow push from build and cosign with manifests (PL-000)
voiceflow/orb-common pull request #238
Opened 2024-05-16 17:00 UTC by theProf

### Brief description. What is this change?
allow image push from build instead of converting and loading into docker locally
`cosign` with remote manifests on digest instead of labels

2024-05-16 17:02 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:58fe8bb19c0f3e316cd935e9d93254f9321cb437

2024-05-16 17:53 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:adad30dce1d5377ea54a7662a35de8ac1ec61c86

2024-05-16 18:14 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:e184704b0fdd4b35b963931845af49b16c210602

2024-05-16 19:29 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:3dea3c861934b2fd4bfee9e98c70d812e3607a86

2024-05-16 20:05 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:68b8b780cdf8e5e9ceca05205da207d5adc1c4a9

2024-05-16 20:56 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f4108ebe1e7860d71d391c5e6147f47edb56ea4a

2024-05-16 20:58 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:1bd7862eb62c19b9739a62e5dae14c06ec0d3241

2024-05-17 14:42 UTC, edison-vflow commented
Does this work for other repos like `creator-app` and `general runtime` ?

2024-05-17 15:03 UTC, xavidop requested changes
can we test this in creator-app, general-runtime, platform to make sure it works before merging?

Link to the executions before merging so we will review it

2024-05-17 17:17 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:7383588b88aa002a1193b822cd2e2a2fc75be307

2024-05-21 13:51 UTC, xavidop approved these changes

2024-05-21 13:51 UTC, merged