feat: added feature to upload chart to ECR
voiceflow/orb-common pull request #239
Opened 2024-05-19 19:20 UTC by junydania

**Fixes or implements IN-1055**

### Brief description. What is this change?

Refactor helm publish action to push to ECR

### Implementation details. How do you make this change?

### Setup information

### Deployment Notes

### Related PRs

- https://github.com/voiceflow/XXXXXXXXX/pull/123

### Checklist

- [ ] Breaking changes have been communicated, including:
    - New required environment variables
    - Renaming of interfaces (API routes, request/response interface, etc)
- [ ] New environment variables have [been deployed](https://www.notion.so/voiceflow/Add-Environment-Variables-be1b0136479f45f1adece7995a7adbfb)
- [ ] Appropriate tests have been written
    - Bug fixes are accompanied by an updated or new test
    - New features are accompanied by a new test

2024-05-20 12:02 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:8ae99ee3d53aaa3c069446a885aabb7226d75b21

2024-05-21 16:07 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:1e9dc6d761353535cf26d9515c022902f1afd155

2024-05-21 20:23 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:6214bb657bed0dccebbce9c489b4279f7cdf03d4

2024-05-21 22:57 UTC, xavidop requested changes

2024-05-21 22:57 UTC, xavidop commented on src/jobs/helm/helm-publish-charts-ecr.yaml
> +  - run: *package-publish-charts-ecr
why is it executed twice?

2024-05-22 00:56 UTC, edison-vflow commented on src/scripts/helm/publish-prerelease-ecr.sh
> +for file in * ; do
Why is the logic for releases and pre-releases different.
For charts we loop over `for chart in ${CHARTS?}; do` and for pre-releases we loop over `for file in * ; do`
Is not the fundamental difference that the chart repo is different but the release logic would be close to similar as well ?
I dont know much here but just wondering why a change of the repo would change the way we also package the charts

2024-05-23 11:40 UTC, junydania commented on src/jobs/helm/helm-publish-charts-ecr.yaml
> +  - run: *package-publish-charts-ecr
Fixed

2024-05-23 11:40 UTC, junydania commented on src/scripts/helm/publish-prerelease-ecr.sh
> +for file in * ; do
Good question.. The logic seems the same but just probably naming I guess

2024-05-23 11:42 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:516fb274da961a80843ddba407b5f500ca7169a6

2024-05-23 11:50 UTC, xavidop approved these changes

2024-05-23 17:03 UTC, merged

2024-05-23 17:04 UTC, vf-service-account commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=0.70.0