feat: improve smoke tests visibility (IN-1101)
voiceflow/orb-common pull request #250
Opened 2024-06-05 05:40 UTC by edison-vflow

### Fixes or implements 
* IN-1101
### Brief description. What is this change?

### Checklist

- [ ] Breaking changes have been communicated, including:

2024-06-05 05:49 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:e1b0bf84d5ccb556299bde7df17da215692a279b

2024-06-05 10:36 UTC, xavidop requested changes

2024-06-05 10:36 UTC, xavidop commented on src/jobs/e2e/collect-e2e-logs.yml
> +  - run: |
add the name to this step

2024-06-05 15:35 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:075f033ec53d96d9b312d26cebb04c6db38fa8c3

2024-06-05 16:17 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:cb97b44714e1976752343fedd776a1752e712fe3

2024-06-05 16:42 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:cfaeb4b6c4b56a0af104153464c0a0811bc57a23

2024-06-05 16:58 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f4c0298a581d35550b841ef581bdbdb4e52c2347

2024-06-05 17:27 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:734856f5888c18a230a71b05f5bc9e7355d73c43

2024-06-05 18:57 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:7f2eaf7db693d29def5b705d1a9cd4bd458719b6

2024-06-05 23:56 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:e2e90b216168c466265cbc8f1be1bc5de01fe29c

2024-06-05 23:58 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:1c2ade90411e7041214b931e747062ad23c4dc98

2024-06-06 00:09 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:068a24ee36016553dd64e18964d9eec61c5e54d8

2024-06-06 07:29 UTC, xavidop approved these changes
GREAT JOB!

2024-06-06 11:29 UTC, junydania approved these changes

2024-06-06 14:10 UTC, merged

2024-06-06 14:11 UTC, vf-service-account commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=0.72.0

2024-06-06 15:32 UTC, theProf commented on src/jobs/e2e/collect-e2e-logs.yml
> +         # Handle the last component separately to introduce blocking.If all components' log collection is done as non blocking tasks,
This is actually slightly different from the previous situation, as this only blocks on the last command, so if the last command is the fastest, the others will not complete. Love what you're doing in both, but you can actually simplify both:
- loop through all (not just n-1)
- call `wait`

`wait` will wait for all children background processes of the current process to complete before continuing. if you want to be extra extra careful, you could store the pids and add them as args, but that would probs be overkill. will add an example above

2024-06-06 15:36 UTC, theProf commented on src/jobs/e2e/collect-e2e-logs.yml
> +            stern -n "${DEV_ENV_NAME:?}" -l "app.kubernetes.io/name=$last_component" >>"${LOG_DIR:?}/${COMPONENT_LOG_DIR:?}/$last_component.log" --since 5m
```
             for component in $components ; do
                echo "Capturing logs for component $component"
                stern -n "${DEV_ENV_NAME:?}" -l "app.kubernetes.io/name=$component" >>"${LOG_DIR:?}/${COMPONENT_LOG_DIR:?}/$component.log" --since 5m &
            done
            wait
```