fix: try treeless clone (ENG-48)
voiceflow/orb-common pull request #261
Opened 2024-06-29 17:01 UTC by DecathectZero

2024-06-29 17:04 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:b213d4a77b52d7d3c594bbf20983fc2d9286b371

2024-06-29 17:14 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:05cc5b45349a0f6f0fec289a2beecc3916894333

2024-06-29 17:35 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:bf19a681a054a8595b34c5d3e1158593cc8fcaf4

2024-06-29 17:39 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:9d498e23194a719c0d88e2e2c697f6f91f6c228e

2024-06-29 17:39 UTC, DecathectZero commented on src/commands/track/update_track.yml
> +            clone_type: treeless
we are changing here from a traditional circleCI clone to a treeless one.

2024-06-29 17:40 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:0407bf0e8cb5681c9a9e0ff08ee85ef67051c048

2024-07-01 05:25 UTC, edison-vflow commented
Hi @DecathectZero 

Great work !

There were errors detected last time across different repos, so we just need to do due diligence and ensure we are all good.
This is what we did last time to ensure we didnt break anything.
Errors were picked up and resolved in this first round of testing.
Even after first round of testing, there were issues we still had to resolve, with `libs` and design `repos` 

So we cant release these changes until we test across all the below repos.


* https://docs.google.com/spreadsheets/d/1K3MIztu0hxk6CB2AFxeonu9FqLGFQEQL5-pllRbywyo/edit?gid=0#gid=0
* We need to do at least one pass where we do a `bors try` to all the repos as there are some nuances to testing some of those repos

The gotchas and some things that were discovered are documented in [this](https://www.notion.so/voiceflow/Shallow-clone-across-all-repos-9e4f6402bcbe4f3f925f583c61c0ec82) notion page 

* We also need to test database-cli as a special case as its got a workflow that runs on tags after a merge to master has occurred.

So until we have bors tried all repos and done a latest tag testing on database-cli, we cant merge the changes only based on the fact that it works on creator-app

2024-07-01 05:27 UTC, edison-vflow requested changes
Hi @DecathectZero 

Great work !

There were errors detected last time across different repos, so we just need to do due diligence and ensure we are all good.
This is what we did last time to ensure we didnt break anything.
Errors were picked up and resolved in this first round of testing.
Even after first round of testing, there were issues we still had to resolve, with `libs` and design `repos` 

So we cant release these changes until we test across all the below repos.


* https://docs.google.com/spreadsheets/d/1K3MIztu0hxk6CB2AFxeonu9FqLGFQEQL5-pllRbywyo/edit?gid=0#gid=0
* We need to do at least one pass where we do a `bors try` to all the repos as there are some nuances to testing some of those repos

The gotchas and some things that were discovered are documented in [this](https://www.notion.so/voiceflow/Shallow-clone-across-all-repos-9e4f6402bcbe4f3f925f583c61c0ec82) notion page 

* We also need to test database-cli as a special case as its got a workflow that runs on tags after a merge to master has occurred.

So until we have bors tried all repos and done a latest tag testing on database-cli, we cant merge the changes only based on the fact that it works on creator-app

2024-07-01 07:16 UTC, xavidop approved these changes

2024-07-01 12:40 UTC, DecathectZero commented
@edison-vflow so the key thing I think to test for is the individual git commands that each repo uses and see if they still work when you do a fresh treeless clone - that's what I've been trying with the render-config. For example it uses [this](https://github.com/voiceflow/orb-common/blob/20118383e57de7d070c438e76528417036cf500c/src/commands/utils/get_changed_files.yml#L22):
```
FILE_CHANGES="$(git diff --name-status --no-commit-id -r $BASE...$CIRCLE_SHA1)"
```
and I've ran that command locally and verified that it works with a treeless clone.

Tags should not be an issue on treeless clones because all tags are contained - only trees and blobs needs to be re-fetched.

2024-07-01 14:44 UTC, merged

2024-07-01 14:45 UTC, vf-service-account commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=0.74.1

2024-07-01 19:07 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:a1440d6125eaa076d94880be153a6485588ff48f