feat: add asciinema collection to collect-e2e-logs
voiceflow/orb-common pull request #313
Opened 2024-12-06 22:10 UTC by theProf

2024-12-06 22:11 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f9fefcea8eb1991a76a8ce8ae3461f1dba95200f

2024-12-06 22:25 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:080c68f340e0e0b702711bb23d325fd06a48c783

2024-12-06 22:26 UTC, xavidop requested changes

2024-12-06 22:26 UTC, xavidop commented on src/jobs/e2e/collect-e2e-logs.yml
> +        sudo apt update
We can add this to the executoe

2024-12-06 22:31 UTC, theProf commented on src/jobs/e2e/collect-e2e-logs.yml
> +        sudo apt update
yup, wasn't sure if i should add to the node executor, or have a new collector executor. but since that's a lot longer of a process, wanted to test the run here by just installing deps. 
- PoC: https://github.com/voiceflow/platform/pull/1311
- This PR will be just the step changes
- draft of executor changes: https://github.com/voiceflow/infrastructure/pull/818

2024-12-06 22:32 UTC, theProf commented
bors try

2024-12-06 22:32 UTC, theProf commented
bors cancel

2024-12-07 00:03 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:44a34a4ff2d220d6db34ec69d70146e6e12ba887

2024-12-07 17:58 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:c58e7d30ca11e2c6bf7e4122e798cb3362197f45

2024-12-07 20:59 UTC, xavidop approved these changes

2024-12-07 21:52 UTC, merged

2024-12-07 21:53 UTC, vf-service-account commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=0.90.0