feat: add e2e service start test job
voiceflow/orb-common pull request #67
Opened 2022-03-14 18:28 UTC by effervescentia

Adds a new `test_e2e_start_service` job that can be used to start the service under test in an e2e environment (with dependencies such as databases and other services)

2022-03-14 18:53 UTC, effervescentia commented on orb.yml
> +  extract_e2e_logs:
does this make sense @xavidop? since we ignore errors it should just capture logs for all the known services that actually ran as part of the job and ignore all the others

2022-03-14 19:05 UTC, xavidop approved these changes

2022-03-15 06:48 UTC, xavidop requested changes

2022-03-15 06:48 UTC, xavidop commented on orb.yml
> +      initialize:
Can you change it to initialize_database?

2022-03-15 06:51 UTC, xavidop approved these changes

2022-03-15 12:37 UTC, merged