ci: add release action on push to master (IN-306)
voiceflow/orb-common pull request #76
Opened 2022-07-18 21:01 UTC by Xavientois

**Part of IN-306**

### Brief description. What is this change?

Adds a GitHub Actions Workflow to create a new release when changes are pushed to master. This follows the rules of semantic commits, so not all commits will create a new release.

Also updates the CircleCI config to use the new publish command to publish on release.

2022-07-18 21:10 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:39103a61ebe819e6a60ee3de2f6e36107d9ac87c

2022-07-19 08:23 UTC, xavidop requested changes
I like this! good job!

2022-07-19 12:54 UTC, Xavientois commented on .github/release.yaml
> +          tag-prefix: voiceflow/common@
Good catch, this is not actually the prefix we want. I will remove it in favour of the default `v` that actually matches what is in the CircleCI docs

2022-07-19 12:54 UTC, Xavientois commented on .github/release.yaml
> +      - name: Create Release
The previous job just generates the release description

2022-07-19 12:58 UTC, Xavientois commented on .github/release.yaml
> +      - name: Create Release
This pattern is from the examples in the Readme [here](https://github.com/TriPSs/conventional-changelog-action)

2022-07-19 13:35 UTC, merged