ci: use new orb packing to deploy orb (IN-303)
voiceflow/orb-common pull request #77
Opened 2022-07-19 20:38 UTC by Xavientois

**Fixes or implements IN-303**

### Brief description. What is this change?

This extracts all of the executors, jobs, and commands from the massive orb file and breaks it up into separate files to allow for orb packing

### Implementation details. How do you make this change?

I wrote a CLI tool to automate the process after I realized how slow it was to do it manually. @xavidop we might consider making my CLI tool open-source for anyone else who wants to perform a similar migration. I didn't find any similar tools online.

### Setup information

### Deployment Notes

### Checklist

- [ ] this is a breaking change and should publish a new major version
- [ ] appropriate tests have been written

2022-07-19 21:13 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:a8b8daa610bb6a60765b30f8c20d2bb0486d05c2

2022-07-19 21:46 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:d94926218c31d3bf270266023eb47dd4332436de

2022-07-19 21:48 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:5f1e1315c4a8d506d179cff098f74e6c6b8d6d76

2022-07-20 07:56 UTC, xavidop requested changes
great job!!! I love the new structure! is super clean!

2022-07-20 07:56 UTC, xavidop commented on .circleci/config.yml
> +            pwd
remove these debug commands

2022-07-20 07:56 UTC, xavidop commented on .circleci/config.yml
> +    docker:
use one of our executors

2022-07-20 07:56 UTC, xavidop commented on .circleci/config.yml
> +      - persist_to_workspace:
is this needed?

2022-07-20 12:47 UTC, Xavientois commented on .circleci/config.yml
> +    docker:
Do we have an executor that is more lightweight than busybox?

2022-07-20 13:56 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:b8237a66c380eb5c3c66b39081242daf42c3a6fc

2022-07-20 13:58 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:546ea72308b36b273b354b88f57f71fa6eb6ecf0

2022-07-20 13:59 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:12daa6ed751f667edca671095ada1e5f40a7c537

2022-07-20 14:35 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:53ede479bfb89999a8508b479dac64fe9c5c6c1c

2022-07-20 14:53 UTC, xavidop approved these changes
WAY TO GO!

2022-07-20 14:55 UTC, merged