feat: extract shell scripts (IN-304)
voiceflow/orb-common pull request #82
Opened 2022-07-20 21:01 UTC by Xavientois

**Fixes or implements IN-304**

### Brief description. What is this change?

Extracts longer shell scripts into external files to allow for reuse of scripts (like `scripts/e2e/setup-database.sh`).

This will also allow for linting of shell scripts.

2022-07-21 11:21 UTC, xavidop requested changes
is this finished yet? I am missing a bunch of shell scripts. I don't like too much the current structure. I would like to have the scripts in the same directory as the command with the same name. Example, down src/jobs/cdk:
1. cdk-deploy.yml
2. cdk-deploy.sh

2022-07-21 12:51 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:0667941c31e45a0764af4e2fefe7e3c0fde70dfa

2022-07-21 16:05 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:50a633f0886b273001c622ac7464c794a38d4ec9

2022-07-21 17:26 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:048aad0ac503a21ede00b5551e8e50461cf55605

2022-07-21 17:52 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f8ae7503aa7f7b6da4d4bc2e1b83ce8fbfb0bef3

2022-07-21 19:45 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:4125b5ff493b519a392b459a4c87b43b8579fb8c

2022-07-21 21:03 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:488a4e74839d66af9fc55e1cdf7dc2abf562e0ac

2022-07-22 15:02 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:6837b1e345c786926cd2a7b45d5ebf2bfac4a46e

2022-07-22 15:03 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:0563d78e51f019d36e7de9973e1f2cfd700bd3e4

2022-07-22 15:11 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:149904d16c95be94f4e9a49f53a6278a1f796fac

2022-07-22 16:18 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:85600c8adfb3bcf6bacef3de38d76301d7e42a8f

2022-07-22 16:28 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:065c291f307101fe71437cab0ce1deb8322a25df

2022-07-22 16:29 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:3ead7b9a32242fd046bb39576c2a94ff64428889

2022-07-22 16:29 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:505dc42832e3becae9b6762dd4094a9f56ebc43b

2022-07-22 16:50 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:e492e3e9a378f970e4ac3d37fbec07e42e61444b

2022-07-22 17:16 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:551de40e8841bb6f0b7952c5fb61e2f3c3d31b24

2022-07-22 17:55 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:1b0be31b09f8d8331bb32424a72b098b4a7c6adb

2022-07-22 18:17 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:76062d71f6044519d86a5697f5afcb32579fd2fd

2022-07-22 18:38 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:c4186bcf1446aa9cb3baeebb8fece3f371b8bf19

2022-07-22 18:45 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:34d344d45ee629373fd4809681ec2f30754915fd

2022-07-22 19:12 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:ad3e27f333bbfea9f0cc6fa5cc5b347ab20e1487

2022-07-22 19:18 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:bae056dee7ffe83291e2948d72687177de53d4c7

2022-07-25 13:30 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:640d94b228f745a536de8c0f4f8c386cee54158a

2022-07-25 13:54 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f51e139cd13be5b19adeb07caf816d37d5c3af3e

2022-07-25 14:10 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:2a946b2230c9a2b08548953efbb79c26aeee8b73

2022-07-25 14:25 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:aea3f194c5c60b762959c190ce892e346faf373f

2022-07-25 14:38 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:6c07554b68d50155266636a74670c8a74ebcd4b4

2022-07-25 14:39 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:676be647172182210ec420c97bd73234995c2289

2022-07-25 15:00 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:b0665c26fdd74bdc29f4c8745e84e6935cf1304b

2022-07-25 21:12 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:dc34139127948b3bbc632f933d08bbbe19eed9db

2022-07-26 08:45 UTC, xavidop requested changes

2022-07-26 08:45 UTC, xavidop commented on src/scripts/utils/exec-with-retry.sh
> -    set -x
why are you enabling debugging here?

2022-07-26 10:48 UTC, Xavientois commented on src/scripts/utils/exec-with-retry.sh
> -    set -x
Oops, I thought I removed that. I put it there when I was debugging it yesterday

2022-10-27 17:06 UTC, Xavientois commented on src/commands/docker/build_push_image.yml
> +      environment:
here

2023-01-03 15:30 UTC, Xavientois commented
Closing this in favour of making these changes incrementally

2023-01-03 15:30 UTC, closed without merging