feat: added turborepo (IN-338)
voiceflow/orb-common pull request #84
Opened 2022-08-07 11:43 UTC by xavidop

**Fixes or implements IN-338**

### Brief description. What is this change?

### Implementation details. How do you make this change?

### Setup information

### Deployment Notes

### Related PRs

- https://github.com/voiceflow/XXXXXXXXX/pull/123

### Checklist

- [ ] this is a breaking change and should publish a new major version
- [ ] appropriate tests have been written

2022-08-07 15:13 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:34dd6684124e79cfaeaf3e6c43df2a912ce594ee

2022-08-07 15:43 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:0c7087c94329ee2b9416fdb66502899730d76edd

2022-08-07 15:54 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:0584f76196afb65227547f9f33860070291f9795

2022-08-07 16:02 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:ea450c0788ffa986b74cf027f4338f04d85105c3

2022-08-07 16:20 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:3c5e00e2c8bc71eedc0d473654281d46c53423a6

2022-08-07 17:00 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:a3fee048c9817cc1351e4fe1e3a184c7adeb48d3

2022-08-07 17:10 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:5481c8f0220cc2ddf47dff120345c245f2eb28ef

2022-08-07 17:19 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:a1e93bee4ebb57daddd653decd51cf60027c4999

2022-08-08 15:56 UTC, Xavientois commented on src/commands/docker/build_push_image.yml
> +            echo -e "Copying yarn.lock file from root"
Why use `-e` here? There are no escaped characters?

2022-08-08 16:00 UTC, Xavientois commented on src/commands/monorepo/monorepo_exec_command.yml
> +                # Work only on folders which the real packages
```suggestion
                # Work only on folders that are real packages
```

2022-08-08 16:06 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:9364ff4071f7a97ac5ae3d2e66a968dff48a36c8

2022-08-08 16:07 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:52fd8ff1f7655b8a05fc932f7a9369dc90210405

2022-08-08 17:01 UTC, Xavientois commented on src/commands/monorepo/monorepo_restore_cache.yml
> +    description: Package folder
Copy paste?

2022-08-08 17:04 UTC, Xavientois commented on src/commands/monorepo/monorepo_restore_cache.yml
> +                      rsync -auv /tmp/build_cache/ .
Can we use the long form, since I don't know what `-auv` does without checking the manpage

2022-08-08 17:04 UTC, Xavientois commented on src/commands/monorepo/monorepo_save_cache.yml
> +    description: Package folder
Copy paste?

2022-08-08 17:07 UTC, Xavientois commented on src/commands/monorepo/monorepo_save_cache.yml
> +                    mkdir -p /tmp/build_cache
```suggestion
                    mkdir --parents /tmp/build_cache
```

2022-08-08 17:09 UTC, Xavientois commented on src/commands/monorepo/monorepo_save_cache.yml
> +                    find ./<< parameters.package_folder >>/*/{build,*.tsbuildinfo} -print0 | rsync -a --files-from=- --from0 . /tmp/build_cache
```suggestion
                    find ./<< parameters.package_folder >>/*/{build,*.tsbuildinfo} -print0 | rsync --archive --files-from=- --from0 . /tmp/build_cache
```

2022-08-08 17:12 UTC, Xavientois commented on src/commands/monorepo/monorepo_save_cache.yml
> +                    - node_modules/.cache
What is this for? Is it not redundant with `save_cache`?

2022-08-08 17:14 UTC, Xavientois commented on src/commands/monorepo/monorepo_types_tests.yml
> +    description: Check that allow the command to run on root
```suggestion
    description: Set to `true` to run the command  on root
```

2022-08-08 17:15 UTC, Xavientois commented on src/commands/monorepo/stop_if_no_changes.yml
> +    description: Package folderto check
```suggestion
    description: Package folder to check
```

2022-08-08 17:15 UTC, Xavientois commented on src/commands/track/update_track.yml
> +    description: Package folderto check
```suggestion
    description: Package folder to check
```

2022-08-08 17:16 UTC, Xavientois commented on src/commands/track/update_track.yml
> +                  echo -e "Copying yarn.lock file from root"
```suggestion
                  echo "Copying yarn.lock file from root"
```

2022-08-08 17:18 UTC, Xavientois commented on src/jobs/monorepo/monorepo_release.yml
> +      name: Set Gihhub config
```suggestion
      name: Set Github config
```

2022-08-08 17:20 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:fe258c8de466d6d78b0dea45205b8178fb4ab3be

2022-08-08 17:20 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:78f4bbcdd6afb4a46df3d0cff9d78fc4c7e0c97c

2022-08-08 17:20 UTC, Xavientois commented on src/commands/monorepo/monorepo_restore_cache.yml
> +                - "<< parameters.monorepo_engine >>"
```suggestion
              equal: ["lerna", << parameters.release_engine >>]
```
For better readability

2022-08-08 17:20 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:3b7e838159613f12cbde880c5c9e089c4b638387

2022-08-08 17:20 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:419b66eb2a950d37516b7990580166c588dc4b6d

2022-08-08 17:20 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:10a86e47fd90d357500b2e1a359d5ffe3a44102b

2022-08-08 17:20 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:d465dcf08dc45fba89f0f8036c1867317b59def7

2022-08-08 17:20 UTC, xavidop commented on src/commands/docker/build_push_image.yml
> +            echo -e "Copying yarn.lock file from root"
removed!

2022-08-08 17:21 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:26e6aee28845d135350ac14af095f459fd78c66a

2022-08-08 17:22 UTC, Xavientois commented on src/commands/monorepo/monorepo_save_cache.yml
> +                - "<< parameters.monorepo_engine >>"
```suggestion
              equal: ["lerna", << parameters.monorepo_engine >>]
```

2022-08-08 17:22 UTC, Xavientois commented on src/commands/monorepo/monorepo_save_cache.yml
> +                - "<< parameters.monorepo_engine >>"
```suggestion
              equal: ["turborepo", << parameters.monorepo_engine >>]
```

2022-08-08 17:23 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:1a339a586f7d4b349f0ab6239f0d99b0f75604e0

2022-08-08 17:23 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:35bbf22c03d35cb1c1e5ee2be9907ae06b2340cc

2022-08-08 17:23 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f28631af850cef500b11a4e56a25e2e8ac0e4ed1

2022-08-08 17:23 UTC, Xavientois commented on src/jobs/track/check_track_exists.yml
> +    description: Monorepo package.
```suggestion
    description: Monorepo package
```

2022-08-08 17:24 UTC, Xavientois commented on src/jobs/track/update_track.yml
> +    description: Package folderto check
```suggestion
    description: Package folder to check
```

2022-08-08 17:26 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:cdce3aca25865e1ed13358e57e965e73ef57ecf5

2022-08-08 17:26 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:95df6fdab3cf9e11f8b2b41b8c70d83e6498d530

2022-08-08 17:26 UTC, Xavientois commented on validate.sh
> +
What is this file for?

2022-08-08 17:26 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:73eb1eee19494c9fbbace7de4af9c78e736ca8c0

2022-08-08 17:30 UTC, Xavientois commented on src/commands/monorepo/monorepo_restore_cache.yml
> +          - "<< parameters.package >>"
```suggestion
        equal: ["all", "<< parameters.package >>"]
```

2022-08-08 17:30 UTC, Xavientois commented on src/commands/monorepo/monorepo_save_cache.yml
> +          - "<< parameters.package >>"
```suggestion
        equal: ["all", "<< parameters.package >>"]
```

2022-08-08 17:31 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:5afbffda76b47d080590264261eb0bb649b2b866

2022-08-08 17:31 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:8df2a5803f488de3bb5710cefb6a9f8127ca644d

2022-08-08 17:33 UTC, Xavientois requested changes
A couple questions and changes, but looks solid overall.

Have you tested it yet? If so, where?

2022-08-08 17:34 UTC, xavidop commented
> A couple questions and changes, but looks solid overall.
> 
> Have you tested it yet? If so, where?

I addressed your changes already. You can find the changes on adapters and platform monorepos:

https://github.com/voiceflow/adapters
https://github.com/voiceflow/platform

2022-08-08 17:51 UTC, Xavientois commented on src/commands/monorepo/monorepo_restore_cache.yml
> +    description: Package folder
@xavidop

2022-08-08 17:52 UTC, Xavientois commented on src/commands/monorepo/monorepo_restore_cache.yml
> +                      rsync -auv /tmp/build_cache/ .
@xavidop

2022-08-08 17:52 UTC, Xavientois commented on src/commands/monorepo/monorepo_save_cache.yml
> +    description: Package folder
@xavidop

2022-08-08 17:52 UTC, Xavientois commented on validate.sh
> +
@xavidop

2022-08-08 17:56 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:5bc917ad746dfc4279556bb77f8c93de0a29e7a4

2022-08-09 09:16 UTC, xavidop commented
@Xavientois can you approve the PR?

2022-08-09 14:35 UTC, Xavientois commented on src/commands/monorepo/monorepo_restore_cache.yml
> +                      rsync -auv /tmp/build_cache/ .
```suggestion
                      rsync --archive --update --verbose /tmp/build_cache/ .
```

2022-08-09 14:37 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:dce7125799b1d3009a2b52a8e8300dab7774547c

2022-08-09 14:37 UTC, Xavientois approved these changes

2022-08-09 14:38 UTC, merged

2022-08-09 14:39 UTC, vf-service-account commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=0.4.0

2022-08-11 21:00 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:e9030ff7c5cfd3a3fa5b54fa1db619d4ba611690