feat: add helm beta release
voiceflow/orb-common pull request #94
Opened 2022-09-06 19:30 UTC by Xavientois

**Fixes or implements VF-XXX**

### Brief description. What is this change?

### Implementation details. How do you make this change?

### Setup information

### Deployment Notes

### Related PRs

- https://github.com/voiceflow/XXXXXXXXX/pull/123

### Checklist

- [ ] this is a breaking change and should publish a new major version
- [ ] appropriate tests have been written

2022-09-06 19:32 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:39bd6330602f44d31bb8e94c3ef64b1255cf632d

2022-09-06 19:44 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:2dabb39223226694651acc3ee4db8eb3a944ee34

2022-09-06 19:47 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:698feb0981b776a919cc9c5851f70c7d20c57762

2022-09-06 20:04 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f9a440f3f470090cb01bfc36cb312c32a4fb352f

2022-09-07 14:55 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f9a440f3f470090cb01bfc36cb312c32a4fb352f

2022-09-07 15:46 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:02a6dff76b03df3e8364b45117dfc6cf15ab07f2

2022-09-07 16:29 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:e5026cd1f923e312bfbb9475c100ec1346bc7f3d

2022-09-07 17:02 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:e1c3f13e76ae78a19bfefc247c108947a75249d2

2022-09-07 17:45 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:971f12908be9ec85b4d05b32b0b5a38088642041

2022-09-07 17:47 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:5fba96f9958f31ca0be522b7ca31ad33c068b16c

2022-09-08 19:29 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:9a6cd47f8fb6e1b3a3d35ecf5fd09abe2424878f

2022-09-08 19:33 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:2864b6f1d074350248520826bb333bf6ef72f6b6

2022-09-09 09:14 UTC, xavidop requested changes

2022-09-09 09:14 UTC, xavidop commented on src/scripts/helm/publish-prerelease.sh
> +done
can we merge this code with the one in the command in helm-package-publish-charts ?

2022-09-09 13:23 UTC, Xavientois commented on src/scripts/helm/publish-prerelease.sh
> +done
As discussed in our call, we will keep these files separate, but I will add a comment that refers to the other one in order to help future maintainers

2022-09-09 14:27 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:3e9f7553ce8dd00f9d5c63284720446a19272291

2022-09-09 14:29 UTC, merged

2022-09-09 14:30 UTC, vf-service-account commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=0.6.0