feat: add node + postgres executor for SDK codegen (vf-000)
voiceflow/orb-common pull request #97
Opened 2022-09-22 09:29 UTC by effervescentia

### Brief description. What is this change?

Adding a new `node-postgres-executor` which is the same as `node-executor` but it has postgres
This will be used in codegen for SDK libraries (unfortunately we need to run the NestJS service to generated these)

### Checklist

- [ ] this is a breaking change and should publish a new major version
- [ ] appropriate tests have been written

2022-09-22 10:36 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:13aecdfc7948f93fe3552c31d0edc96722a965dd

2022-09-22 16:30 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:f30d596b8fa4b58ec3d6872cbf887d8436be8a55

2022-09-23 18:33 UTC, effervescentia commented on src/executors/node/node-build-executor.yml
> +    default: large
this is the only difference from `node-executor`

2022-09-23 18:33 UTC, effervescentia commented on src/executors/node/node-postgres-executor.yml
> +  - image: postgres:10.6-alpine # PostgresDB service container
the addition of postgres here is the only difference from `node-executor`

2022-09-23 18:33 UTC, effervescentia commented on src/jobs/yarn/install_and_build.yml
> +    default: node-build-executor
had to create `node-build-executor` just for this purpose because the following "isn't valid" according to circle CI

```
executor:
    description: The executor used to run this job
    type: executor
    default:
      name: node-build-executor
      default_resource_class: large 
```

2022-09-23 18:33 UTC, effervescentia commented on validate.sh
> +for DIR in commands jobs executors; do
noticed some errors while running this locally because `examples` doesn't exist

2022-09-23 18:49 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:1c4b7f6512b618f90e8bf8fba0dcd77cc18087e6

2022-09-26 19:36 UTC, xavidop requested changes
why dont you use the e2e executor?

2022-10-05 19:41 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:1fc597da4f837cfbc27498e264830811b8b89cf6

2022-10-05 19:49 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:b1ad1bfa00ff596b10f3462ef4fac9b2ffaee8e1

2022-10-05 19:50 UTC, effervescentia commented
> why dont you use the e2e executor?

I tested it out and it works perfectly 👍 switched to that so I removed the `node-postgres-executor`

2022-10-05 19:57 UTC, xavidop requested changes
the node-build-executor is the same as node-executor. why dont we use that one isntead?

2022-10-05 19:58 UTC, xavidop commented
sorry, same as `build-executor`

2022-10-06 06:35 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:0eeaccf6ffb3bea7d11d47ae86ae83af0572daa9

2022-10-06 18:49 UTC, vf-service-account commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=dev:9dbd27d670fd0c8651d58c11f7889b423746bf3f

2022-10-06 18:50 UTC, xavidop approved these changes

2022-10-06 18:51 UTC, merged

2022-10-06 18:52 UTC, vf-service-account commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/voiceflow/common?version=0.9.0